[alembic]
script_location = alembic
prepend_sys_path = .
version_path_separator = os

sqlalchemy.url = postgresql://sandguard:sandguard_secret_pass@localhost:5432/sandguard_db

[logging]
default_level = INFO
